### PR TITLE
README.md: Clarification on Running

### PR DESCRIPTION
**Pull request by cclauss**

### CODE REVIEW

**Review by abraha2d — APPROVED** [review]

**Comment by abraha2d** [comment]
That last commit adds running `sistine.py` in 2 places?

**Review by abraha2d — CHANGES_REQUESTED** [review]
That last commit adds running sistine.py in 2 places? Now it exists both under "Installation", and under "Running".

**Comment by cclauss** [comment]
@abraha2d Are you OK with the last updates?

**Review by abraha2d — APPROVED** [review]

**Comment by antimatter15** [comment]
Thanks!

**Pull request merged**
