### PR TITLE
print() is a function in Python 3

### PR DESCRIPTION
**Pull request by cclauss**
Also:
* Sort imports with __isort__
* Comment out unused imports and variables
* Some whitespace changes for PEP8

### CODE REVIEW

**Comment by afraca** [comment]
By default MacOS ships with Python 2 unfortunately. And I think homebrew puts python 3 as `python3` in your PATH, not `python`.

**Comment by cclauss** [comment]
Given that all the Linuxs are shifting to Python 3 as default, I would bet that some OSX upgrade soon will do the same.  My advise is to make the code compatible with both before that day comes.  https://pythonclock.org

**Comment by cclauss** [comment]
https://docs.brew.sh/Homebrew-and-Python says "_python points to Homebrew’s Python 2.7.x (if installed) otherwise the macOS system Python._".  The problem is that that Python does not have Quartz pip installed.  See the other PR.

**Comment by cclauss** [comment]
Macs defaulting to Python 2 will soon be a thing of the past.  Will this repo be modernized soon?

**Pull request closed without merging**
